#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CMD="clear && $*"

ITERM_EXISTS=`osascript <<EOF
set doesExist to false
try
    do shell script "osascript -e 'id of application \"iTerm\"'"
    set doesExist to true
end try
return doesExist
EOF`

function open_iterm () {
  osascript <<EOF
  tell application "iTerm"
    activate

    tell current window
        create tab with default profile
        tell current tab
            repeat with aSession in sessions
                tell aSession
                    write text "bash -c \"$CMD\""
                end tell
            end repeat
        end tell
    end tell
  end tell
EOF
}

function open_terminal () {
  osascript > /dev/null <<EOF
  tell application "Terminal" to activate
  delay 0.4
  tell application "System Events" to keystroke "t" using command down
  tell application "Terminal"
    do script "bash -c \"$CMD\"" in window 1
  end tell
EOF
}

if [ "$ITERM_EXISTS" == "true" ]; then
  open_iterm "$@"
else
  open_terminal "$@"
fi
